apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-controller-operatorsdk
spec:
  replicas: 1
  selector:
    matchLabels:
      name: foo-controller-operatorsdk
  template:
    metadata:
      labels:
        name: foo-controller-operatorsdk
    spec:
      serviceAccountName: foo-controller-operatorsdk
      containers:
        - name: foo-controller-operatorsdk
          # Replace this with the built image name
          image: govargo/foo-controller:operatorsdk
          command:
          - foo-controller-operatorsdk
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "foo-controller-operatorsdk"
